name: unsplash_gallery
description: Unsplash-Gallery ” --org com.dinnova.unsplash_gallery”
version: 1.0.1+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  dio: ^4.0.6
  dartz: ^0.10.1
  connectivity_plus: ^4.0.2
  get_it: ^7.6.0
  injectable: ^2.2.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.2.0
  easy_localization: ^3.0.2
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  flutter_easyloading: ^3.0.5
  path_provider: ^2.1.0
  another_flushbar: ^1.12.30
  flutter_dotenv: ^5.0.2
  permission_handler: ^10.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  # add the generator to your dev_dependencies
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/